[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
soltip = "9UXhm3zakFtqXYYgEuT2VQhhp7ots23N52PHKxynFCZ9"

[programs.devnet]
soltip = "9UXhm3zakFtqXYYgEuT2VQhhp7ots23N52PHKxynFCZ9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
